services:
  web:
    build:
      context: vuejs
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./vuejs:/project
      - /project/node_modules

  backend:
    build:
      context: fastapi
      target: builder
    # fastapi requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./fastapi:/src
    depends_on:
      -  database
    ports:
      - 8000:8000

  database:
    container_name: postgres_database
    image: timescale/timescaledb:2.10.3-pg15
    restart: always
    ports:
      - 8010:8010
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pgdatabase
      - TIMESCALEDB_TELEMETRY=off

    volumes:
      - ./postgres/data:/var/lib/postgresql/data


