version: '3.5'

services:
  nfa_db:
    image: timescale/timescaledb:2.11.0-pg15
    container_name: nfa_db_standalone
    command: postgres -c shared_preload_libraries=timescaledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:7.2.1
    container_name: nfa_redis
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data